services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/certs/cert.pem:/etc/ssl/certs/cert.pem
      - ./frontend/certs/key.pem:/etc/ssl/private/key.pem
    depends_on:
      - frontend
    deploy:
      resources:
        limits:
          memory: 1g

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - api
    deploy:
      resources:
        limits:
          memory: 1g
    volumes:
      - ./logs:/logs

  api:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "5000"
    environment:
      - OPENAI_RKI_KEY=${OPENAI_RKI_KEY}
    deploy:
      resources:
        limits:
          memory: 12GB
    volumes:
      - ./logs:/logs

