services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/certs/cert.pem:/etc/ssl/certs/cert.pem
      - ./frontend/certs/key.pem:/etc/ssl/private/key.pem
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - api-sitzungsprotokolle
      - api-zusatzmaterial

  api-sitzungsprotokolle:
    build:
      context: .
      dockerfile: Dockerfile-Sitzungsprotokolle.api
    expose:
      - "5000"
    environment:
      - OPENAI_RKI_KEY=${OPENAI_RKI_KEY}
    deploy:
      resources:
        limits:
          memory: 2g

  api-zusatzmaterial:
    build:
      context: .
      dockerfile: Dockerfile-Zusatzmaterial.api
    expose:
      - "5000"
    environment:
      - OPENAI_RKI_KEY=${OPENAI_RKI_KEY}
    deploy:
      resources:
        limits:
          memory: 8g
